OnlineShop/OnlineShopWebApp/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShopWebApp.Helpers;
using System;
using System.Collections.Generic;


namespace OnlineShopWebApp.Controllers
{
    public class CartController : Controller
    {
        private readonly IProductsStorage productStorage;
        private readonly ICartsStorage cartsStorage;

        public CartController(IProductsStorage productStorage, ICartsStorage cartsStorage)
        {
            this.productStorage = productStorage;
            this.cartsStorage = cartsStorage;
        }       

        public IActionResult Index()
        {
            var cart = cartsStorage.TryGetByUserId(Constants.UserId);
            return View(Mapping.ToCartViewModel(cart));
        }
        public IActionResult Add(Guid productId)
        {
            var product = productStorage.TryGetById(productId);
            cartsStorage.Add(product, Constants.UserId);
            return RedirectToAction("Index");
        }

        public IActionResult DecreaseAmount(Guid productId)
        {           
            cartsStorage.DecreaseAmount(productId, Constants.UserId);
            return RedirectToAction("Index");
        }

        public IActionResult Clear()
        {
            cartsStorage.Clear(Constants.UserId);
            return RedirectToAction("Index");
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ComparingController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShopWebApp.Helpers;
using System;

namespace OnlineShopWebApp.Controllers
{
    public class ComparingController : Controller
    {
        private readonly IProductsStorage productStorage;
        private readonly IComparingStorage comparingStorage;
        public ComparingController(IProductsStorage productStorage, IComparingStorage comparingStorage)
        {
            this.productStorage = productStorage;
            this.comparingStorage = comparingStorage;
        }

        public IActionResult Index()
        {
            var comparingProduct = comparingStorage.GetAll(Constants.UserId);
            return View(Mapping.ToProductViewModels(comparingProduct));
        }
        public IActionResult Add(Guid id)
        {
            var existingProduct = productStorage.TryGetById(id);
            comparingStorage.Add(Constants.UserId, existingProduct);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(Guid id)
        {
            var existingProduct = productStorage.TryGetById(id);
            comparingStorage.Remove(Constants.UserId, id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/FavoritesController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShopWebApp.Helpers;
using System;

namespace OnlineShopWebApp.Controllers
{
    public class FavoritesController : Controller
    {

        private readonly IProductsStorage productStorage;
        private readonly IFavoritesStorage favoritesStorage;
        public FavoritesController(IProductsStorage productStorage, IFavoritesStorage favoritesStorage)
        {
            this.productStorage = productStorage;
            this.favoritesStorage = favoritesStorage;
        }

        public IActionResult Index()
        {
            var favoriteProduct = favoritesStorage.GetAll(Constants.UserId);
            return View(Mapping.ToProductViewModels(favoriteProduct));
        }
        public IActionResult Add(Guid id)
        {
            var existingProduct = productStorage.TryGetById(id);
            favoritesStorage.Add(Constants.UserId, existingProduct);

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Remove(Guid id)
        {
            var existingProduct = productStorage.TryGetById(id);
            favoritesStorage.Remove(Constants.UserId, id);
            return RedirectToAction(nameof(Index));
        }
    }
}

OnlineShop/OnlineShopWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using OnlineShopWebApp.Helpers;

namespace OnlineShopWebApp.Controllers
{
    public class HomeController : Controller
    {

        private readonly IProductsStorage productStorage;
        public HomeController(IProductsStorage productStorage)
        {
            this.productStorage = productStorage;
        }

        public IActionResult Index()
        {
            
            var products = productStorage.GetAll();                        
            return View(Mapping.ToProductViewModels(products));
        }
       
    }
}

OnlineShop/OnlineShopWebApp/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShop.Db;
using System;
using System.Collections.Generic;


namespace OnlineShopWebApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductsStorage productStorage;

        public ProductController(IProductsStorage productStorage)
        {
            this.productStorage = productStorage;
        }       
        public IActionResult Index(Guid id)

        {
            var product = productStorage.TryGetById(id);
            return View(product);
        }


        //public string Index(Guid id)
        //{
        //    var product = productStorage.TryGetById(id);

        //    if (product == null)
        //    {
        //        return $"Продукта с номером {id} нет в каталоге! Выберите другой номер.";
        //    }

        //    return $"{product}\n{product.Description}";

        //}

    }
}

OnlineShop/OnlineShopWebApp/Views/Home/Index.cshtml
@model List<ProductViewModel>
@{ ViewData["Title"] = "Home Page"; }

<div class="row">
    @foreach (var product in Model)
    {
<div class="col-3 card shadow">
    
    <div class="card-body">
        <a class="btn" 
           asp-area=""
           asp-controller="Comparing"
           asp-action="Add"
           asp-route-Id="@product.Id"
           role="button"><img class="figure-img" src="http://s1.iconbird.com/ico/2013/6/289/w512h5121371656132tasks.png" height="40" width="40" /></a>
        <a class="btn"
           asp-area=""
           asp-controller="Favorites"
           asp-action="Add"
           asp-route-Id="@product.Id"
           role="button"><img class="figure-img text-lg-right" src="http://s1.iconbird.com/ico/2013/9/450/w256h2561380453904heart256x25632.png" height="30" width="30" /></a>
        <br />
        <br />
        <img class="card-img-bottom" src="@product.ImagePath" />

    </div>
    <div class="container">
        
        <div class="row align-items-end">

            <div class="col">

                <a style="color:blueviolet" 
                   asp-area=""
                   asp-controller="Product"
                   asp-action="Index"
                   asp-route-Id="@product.Id">
                   <h5>@product.Name</h5></a>
                <h5>@product.Cost руб.</h5><br />
                <a class="btn btn-primary" 
                   asp-area=""
                   asp-controller="Cart"
                   asp-action="Add"
                   asp-route-productId="@product.Id"
                   role="button">Добавить в корзину</a>
                <br />
                <br />
            </div>
        </div>
    </div>
</div>}
</div>